AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: NLP Classification API

Resources:
  NLPFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: lambda_handler.lambda_handler
      Runtime: python3.13
      Timeout: 30
      MemorySize: 1024
      Events:
        NLPApi:
          Type: Api
          Properties:
            Path: /predict
            Method: post
